#!/bin/bash
# printf "Give name of project(no spaces)"
# read $projectname
warning "Will create VirtualHost in Apache http://project.app in ~/Sites/project. Need to modify hosts file & restart Apache"

