#!/bin/bash
clear
source log
source fileutils
source consoleutils

user=$(whoami)

title APACHE
askbefore apache/enablemodrewrite 		"¿Quieres habilitar mod_rewrite?"
askbefore apache/changeuserandgroup 	"¿Quieres cambiar el usuario/grupo de Apache a $user/staff ?"
askbefore apache/personalconfiguration 	"¿Quieres crear un archivo de usuario personal para Apache?"

title PHP
askbefore php/createini 				"¿Quieres crear el archivo php.ini?"
askbefore php/settimezone 				"¿Quieres definir el timezone?"
askbefore php/setsessionstmpfolder 		"¿Cambiar la carpeta donde guarda las sesiones PHP?"

title APACHE
askbefore apache/restart 				"¿Reiniciar Apache?"

title MYSQL
askbefore mysql/install 				"¿Instalar MySQL?"

title APACHE
askbefore apache/addsubdomain 			"¿Quieres añadir un subdominio?"
