#!/bin/bash
# mkdir /Users/raulete/tmp
# sudo nano /private/etc/php.ini
# cambiar
# ;session.save_path = 
# por
# session.save_path = "/Users/raulete/tmp"
source log
source fileutils

info 'Create Personal Folder to Sessions (phpsetsessiontmpfolder)' 
success "Created tmp folder in users' folder"
success "Set session.save_path attribute with folder created before"
