#!/bin/bash
# sudo nano /private/etc/php.ini
# cambiar 
# ;date.timezone = 
# por
# date.timezone = Europe/Madrid
source log
source fileutils

info 'Set timezone (phpsettimezone)' 
warning "Timezone is not Setted"
success "Set dat.timezone to Europe/Madrid"
